@url = http://localhost:8080

###

GET {{url}}/api/login HTTP/1.1
Authorization: Basic designer:designer

###

@token = <the above token>

###

GET {{url}}/api/rest/SystemParam?sys_code=TEST HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{url}}/api/rest/SystemParam?sys_code=TEST HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{url}}/api/rest/SystemParam HTTP/1.1
Authorization: Bearer {{token}}
Content-type: application/json

{
    "sys_code": "TEST",
    "sys_value": "test 1"
}

@id = -1

###

PUT {{url}}/api/rest/SystemParam/{{id}} HTTP/1.1
Authorization: Bearer {{token}}
Content-type: application/json

{
    "sys_value": "test 2"
}

###

DELETE {{url}}/api/rest/SystemParam/{{id}} HTTP/1.1
Authorization: Bearer {{token}}
